### PR TITLE
Updated Download Variable Names

### PR DESCRIPTION
**Pull request by SeanHansell**
Fix for #69 

- Updated variable names on download recipe.
- Ran `plutil` on to ensure formatting

Tested and new variable names do not conflict with JamfUpload variables. Unfortunately users will need to update their overrides, butI don't think there's any way around it.

### CODE REVIEW

**Comment by SeanHansell** [comment]
I renamed all the variables just for consistency's sake, even though only two of them are causing an issue now.

**Comment by vao-brex** [comment]
+1

**Comment by MLBZ521** [comment]
@SeanHansell I'm trying to remove the `.pyc` file and `pycache` directory in this PR, but both from the web and local GitHub app, I'm getting errors.  For some reason, it won't let me as it says your `master` branch is protected -- even though it doesn't appear so when I looked at your fork.

I've submitted a PR on your fork...hopefully that'll work.

**Comment by SeanHansell** [comment]
@MLBZ521 Merged! This should be good to go!

**Comment by MLBZ521** [comment]
Thanks!

**Pull request merged**
